In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [5]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
params_grid={'kernel':['rbf','sigmoid','linear','poly'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),params_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\jeyap\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1368: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear', 'poly']},
             verbose=3)

In [8]:
print("Best Parameters:{}".format(grid.best_params_))

Best Parameters:{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}

In [9]:
print("Best R2 Score:{}".format(grid.best_score_))

Best R2 Score:0.8213633019952449

In [10]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.143632,0.073651,0.151766,0.018662,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,21
1,0.745763,0.432993,0.049999,0.009841,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,22
2,0.340727,0.027402,0.035458,0.005517,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,13
3,3805.368990,592.127470,0.037662,0.003128,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.858852,0.774048,0.862382,0.788049,0.823487,0.821363,0.035892,1
4,0.245133,0.010292,0.132144,0.006695,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,20
5,0.381393,0.070196,0.071434,0.015475,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,27
6,0.308355,0.030447,0.040053,0.005816,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,13
7,0.246573,0.008991,0.039548,0.004693,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,29
8,0.398734,0.007785,0.129329,0.002859,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,19
9,0.224380,0.008901,0.043395,0.002543,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,22
10,0.599973,0.054497,0.035208,0.009467,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,9
11,4934.521776,2481.781754,0.030403,0.008301,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.784924,0.687688,0.775287,0.507052,0.720109,0.695012,0.100539,2
12,0.194998,0.029407,0.092167,0.005143,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,34
13,0.228532,0.019562,0.043604,0.001837,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,32
14,0.387591,0.016368,0.022548,0.002627,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,9
15,0.185813,0.036473,0.025126,0.001606,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,31
16,0.413516,0.022071,0.096014,0.006328,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080692,-0.054347,-0.062876,-0.079329,-0.117983,-0.079045,0.021865,17
17,0.157707,0.015728,0.034126,0.012370,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,22
18,1.437213,0.160796,0.022461,0.001662,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,3
19,3894.758846,1167.189200,0.028960,0.011019,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",-15.085640,-7.827515,-9.886241,-9.199449,-12.489637,-10.897696,2.584811,37
20,0.200234,0.013145,0.089110,0.004214,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,33
21,0.235013,0.020692,0.053266,0.016615,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,35
22,1.450721,0.158857,0.022386,0.000926,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,3
23,0.240709,0.014819,0.024219,0.001785,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,18
24,0.606731,0.052638,0.089889,0.002352,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.033126,-0.002835,-0.026545,-0.029140,-0.067392,-0.031808,0.020699,16
25,0.142492,0.001740,0.027860,0.002105,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,22
26,2.364781,0.179659,0.023551,0.002570,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,5
27,3627.176391,980.725585,0.020643,0.008955,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",-66.911253,-42.837581,-46.649358,-44.378412,-32.275513,-46.610424,11.285664,39
28,0.281291,0.024799,0.118588,0.003114,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,30
29,0.294102,0.027872,0.062085,0.003594,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,36
30,3.243489,0.212320,0.030885,0.001020,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,5
31,0.403905,0.049127,0.037306,0.007660,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",-0.020567,0.035685,-0.011468,-0.024587,-0.076360,-0.019459,0.035693,15
32,1.005411,0.096152,0.130025,0.017607,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.011741,0.043659,0.013383,0.021694,-0.012948,0.015506,0.018217,12
33,0.217500,0.026373,0.036568,0.001489,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,22
34,6.156701,1.125821,0.031844,0.004142,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,7
35,3067.054089,1025.303621,0.017441,0.004675,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",-139.542470,-248.421043,-152.372959,-67.783230,-212.402074,-164.104355,62.386929,40
36,0.326701,0.037596,0.144995,0.016110,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,28
37,0.134454,0.019841,0.024250,0.006350,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,38
38,2.217021,0.448500,0.010577,0.000332,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,7
39,0.194507,0.022635,0.012692,0.001253,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.037700,0.098496,0.049291,0.035615,-0.020924,0.040035,0.038064,11

In [11]:
age_input=int(input('Age:'))
bmi_input=float(input('BMI:'))
children_input=int(input('Children:'))
sex_male_input=int(input('Sex Male 0 or 1:'))
smoker_yes_input=int(input('Smoker Yes 0 or 1:'))

Age: 25
BMI: 35.080
Children: 5
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future Prediction={}'.format(Future_Prediction))

Future Prediction=[33066.64245122]

C:\Users\jeyap\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(