In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [5]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
params_grid={'criterion':['squared_error','absolute_error','poisson'],
            'splitter':['best','random'],
            'max_features':['sqrt','log2',None]}
grid=GridSearchCV(DecisionTreeRegressor(),params_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
print("Best Parameters:{}".format(grid.best_params_))

Best Parameters:{'criterion': 'poisson', 'max_features': None, 'splitter': 'best'}

In [9]:
print("Best R2 Score:{}".format(grid.best_score_))

Best R2 Score:0.7130117922642029

In [10]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.058887,0.016229,0.151639,0.020827,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.671433,0.611514,0.750304,0.676194,0.738379,0.689565,0.050342,7
1,0.031340,0.017168,0.093422,0.072109,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.707614,0.599875,0.581104,0.570916,0.653803,0.622663,0.051207,18
2,0.009585,0.000661,0.005183,0.001557,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.726065,0.541529,0.641540,0.603017,0.771577,0.656746,0.082927,14
3,0.010575,0.001317,0.005341,0.000273,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.718343,0.500603,0.690970,0.651553,0.693487,0.650991,0.078176,15
4,0.012255,0.001336,0.005785,0.000372,squared_error,NaN,best,"{'criterion': 'squared_error', 'max_features':...",0.727596,0.645124,0.742588,0.734948,0.681109,0.706273,0.037331,2
5,0.009194,0.001007,0.005707,0.000716,squared_error,NaN,random,"{'criterion': 'squared_error', 'max_features':...",0.644207,0.609704,0.733466,0.673623,0.668222,0.665844,0.040642,10
6,0.021351,0.001412,0.004719,0.000254,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.739684,0.658606,0.641974,0.734044,0.554156,0.665693,0.068117,11
7,0.017718,0.001617,0.005036,0.000271,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.770395,0.460605,0.786940,0.686237,0.683757,0.677587,0.116418,9
8,0.020091,0.002540,0.004354,0.000496,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.723511,0.552789,0.708603,0.723720,0.716369,0.684999,0.066337,8
9,0.019470,0.002440,0.004656,0.000737,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.710771,0.526287,0.724105,0.575374,0.773929,0.662093,0.094536,13
10,0.026793,0.001758,0.004547,0.000355,absolute_error,NaN,best,"{'criterion': 'absolute_error', 'max_features'...",0.718093,0.632230,0.713796,0.737693,0.727967,0.705956,0.037778,4
11,0.027214,0.002157,0.006176,0.001522,absolute_error,NaN,random,"{'criterion': 'absolute_error', 'max_features'...",0.711638,0.616392,0.734983,0.718821,0.728179,0.702003,0.043538,6
12,0.007899,0.000946,0.004689,0.000395,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.711463,0.614543,0.719427,0.721324,0.763597,0.706071,0.049248,3
13,0.006857,0.000936,0.004415,0.000295,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.724115,0.489779,0.623651,0.722630,0.676450,0.647325,0.086945,16
14,0.009008,0.001284,0.004602,0.000208,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.716990,0.613757,0.706127,0.593530,0.689011,0.663883,0.050395,12
15,0.006923,0.001408,0.004264,0.000556,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.652296,0.550894,0.723846,0.657286,0.621644,0.641194,0.056125,17
16,0.010691,0.001531,0.005061,0.000438,poisson,NaN,best,"{'criterion': 'poisson', 'max_features': None,...",0.746181,0.665422,0.763551,0.713351,0.676554,0.713012,0.038075,1
17,0.007849,0.000830,0.004320,0.000854,poisson,NaN,random,"{'criterion': 'poisson', 'max_features': None,...",0.695232,0.668606,0.696768,0.712431,0.739283,0.702464,0.023178,5

In [11]:
age_input=int(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=int(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 35.080
Children: 5
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction={}".format(Future_Prediction))

Future Prediction=[36397.576]

C:\Users\jeyap\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(